const TEST={unit:'1A',title:'A cappuccino, please',version:'1.0.0'};
const audio={n0:'assets/audio/number_0.mp3',n3:'assets/audio/number_3.mp3',n7:'assets/audio/number_7.mp3',n10:'assets/audio/number_10.mp3',hello:'assets/audio/sound_hello.mp3',five:'assets/audio/sound_five.mp3',nine:'assets/audio/sound_nine.mp3',meet:'assets/audio/sound_meet.mp3',mission:'assets/audio/dialogue_mission.mp3'};
const state=JSON.parse(localStorage.getItem('wow_ef_1a_state')||'null')||{screen:0,answers:{},checked:{},scores:{grammar:[0,0],numbers:[0,0],days:[0,0],pronunciation:[0,0],communication:[0,0]}};
let currentAudio=null; const save=()=>localStorage.setItem('wow_ef_1a_state',JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const meta=(i,total=10)=>`<div class="top"><div class="brand">WOW <span>SCHOOL</span> · ${TEST.unit}</div><div class="progress"><i style="width:${(i/total)*100}%"></i></div><div class="counter">${i}/${total}</div></div>`;
const nav=(i,{check=true,next=true,back=true}={})=>`<div class="nav"><div class="feedback" id="feedback-${i}"></div><div class="right">${back?`<button class="btn ghost" data-prev>← Назад</button>`:''}${check?`<button class="btn green" data-check="${i}">ПРОВЕРИТЬ</button>`:''}${next?`<button class="btn gold" data-next>ДАЛЕЕ →</button>`:''}</div></div>`;
const screens=[];
screens.push(`<section class="screen bg-coffee" data-screen="0">${meta(1)}<div class="hero"><div><h1 class="title">Выберите правильный вариант</h1><p class="subtitle">Choose the correct form of <b>be</b>.</p></div></div><div class="task-zone"><div class="choice-grid" id="grammar-grid"></div></div>${nav(1,{back:false})}</section>`);
screens.push(`<section class="screen bg-violet" data-screen="1">${meta(2)}<div class="hero"><div><h1 class="title">Соберите сокращения</h1><p class="subtitle">Build the contractions.</p></div></div><div class="task-zone"><div class="builder-wrap" id="builder"></div></div>${nav(2)}</section>`);
screens.push(`<section class="screen bg-teal" data-screen="2">${meta(3)}<div class="hero"><div><h1 class="title">Услышьте число</h1><p class="subtitle">Listen and type the number.</p></div></div><div class="task-zone"><div class="audio-card card"><button class="play-orb" id="num-play" aria-label="Play audio">▶</button><div><div class="rounds" id="num-rounds"></div><div class="qtext">Какое число вы слышите?</div><input id="num-input" class="answer-input" inputmode="numeric" autocomplete="off" placeholder="Введите цифру 0–10"><div style="margin-top:14px"><button class="btn green" id="num-submit">ПРОВЕРИТЬ РАУНД</button></div><div class="feedback" id="num-feedback"></div></div></div></div>${nav(3,{check:false})}</section>`);
screens.push(`<section class="screen bg-coffee" data-screen="3">${meta(4)}<div class="hero"><div><h1 class="title">Number Challenge</h1><p class="subtitle">Count, continue, and write.</p></div></div><div class="task-zone"><div class="number-grid" id="number-grid"></div></div>${nav(4)}</section>`);
screens.push(`<section class="screen bg-days" data-screen="4">${meta(5)}<div class="hero"><div><h1 class="title">Дни недели</h1><p class="subtitle">Put the days of the week in order.</p></div></div><div class="task-zone"><div class="days-board white-card" id="days-board"></div></div>${nav(5)}</section>`);
screens.push(`<section class="screen bg-sound" data-screen="5">${meta(6)}<div class="hero"><div><h1 class="title">Разложите слова по звукам</h1><p class="subtitle">Drag each word to /h/, /aɪ/, or /iː/.</p></div></div><div class="task-zone"><div class="sound-zone" id="sound-zone"></div></div><div class="sound-bank" id="sound-bank"></div>${nav(6)}</section>`);
screens.push(`<section class="screen bg-meet" data-screen="6">${meta(7)}<div class="hero"><div><h1 class="title">Meet someone</h1><p class="subtitle">Complete the mini-dialogue.</p></div></div><div class="task-zone"><div class="dialogue white-card" id="dialogue"></div></div>${nav(7)}</section>`);
screens.push(`<section class="screen bg-violet" data-screen="7">${meta(8)}<div class="hero"><div><h1 class="title">Mini Listening Mission</h1><p class="subtitle">Listen to a short meeting and answer.</p></div></div><div class="task-zone"><div class="listening"><div class="listen-panel card"><button class="play-orb" id="mission-play">▶</button><h3>Listen</h3><p class="subtitle">Можно прослушать несколько раз.</p></div><div class="listen-q card" id="mission-qs"></div></div></div>${nav(8)}</section>`);
screens.push(`<section class="screen bg-map" data-screen="8">${meta(9)}<div class="hero"><div><h1 class="title">Ваш прогресс</h1><p class="subtitle">Посмотрите, какие навыки уже закреплены.</p></div></div><div class="task-zone"><div class="skill-map" id="skill-map"></div></div>${nav(9,{check:false})}</section>`);
screens.push(`<section class="screen bg-final" data-screen="9">${meta(10)}<div class="hero"><div><h1 class="title">Отличная работа!</h1><p class="subtitle">Unit 1A завершён.</p></div></div><div class="task-zone"><div class="final-wrap"><div id="score-ring"></div><div class="breakdown card" id="breakdown"></div></div></div><div class="nav"><div class="feedback">Результат сохранён в этом браузере.</div><div class="right"><button class="btn ghost" id="review">ПРОСМОТРЕТЬ ОШИБКИ</button><button class="btn gold" id="restart">ПРОЙТИ ЕЩЁ РАЗ</button></div></div></section>`);
document.querySelector('#app').innerHTML=`<div class="stage">${screens.join('')}<div class="toast" id="toast"></div></div>`;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function show(i){state.screen=Math.max(0,Math.min(9,i));save();$$('.screen').forEach((el,j)=>el.classList.toggle('active',j===state.screen));if(state.screen===8)renderProgress();if(state.screen===9)renderFinal();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function play(src,btn){if(currentAudio){currentAudio.pause();currentAudio=null}const a=new Audio(src);currentAudio=a;if(btn)btn.classList.add('pulse');a.onended=()=>{if(btn)btn.classList.remove('pulse');currentAudio=null};a.play().catch(()=>toast('Нажмите Play ещё раз'))}
function setScore(cat,correct,total){state.scores[cat]=[correct,total];save()}
function feedback(i,msg,ok){const e=$(`#feedback-${i}`);if(!e)return;e.textContent=msg;e.className='feedback '+(ok?'ok':'bad')}
// 1 grammar
const grammar=[['I ___ from Spain.',['am','are'],'am'],['___ you Mr Buchanan?',['Am','Are'],'Are'],['You ___ in my class.',['am','are'],'are'],['___ I in room 4?',['Am','Are'],'Am'],['No, I ___.',["'m not","aren’t"],"'m not"],['Yes, you ___.',['are',"'re"],'are']];
$('#grammar-grid').innerHTML=grammar.map((q,qi)=>`<div class="question card"><div class="qtext">${qi+1}. ${q[0]}</div><div class="options">${q[1].map(o=>`<button class="opt" data-gq="${qi}" data-val="${esc(o)}">${esc(o)}</button>`).join('')}</div></div>`).join('');
$$('[data-gq]').forEach(b=>b.onclick=()=>{const q=b.dataset.gq;$$(`[data-gq="${q}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.answers['g'+q]=b.dataset.val;save()});
//2 builder
const builds=[['I','am',"I’m"],['You','are',"You’re"],['I','am not',"I’m not"],['You','are not',"You aren’t"]];
$('#builder').innerHTML=builds.map((x,i)=>`<div class="build-card card"><div class="formula"><span class="chip">${x[0]}</span><span>+</span><span class="chip">${x[1]}</span><span>→</span></div><select class="inline-select" data-build="${i}"><option value="">Choose</option>${["I’m","You’re","I’m not","You aren’t"].map(v=>`<option>${v}</option>`).join('')}</select></div>`).join('');
$$('[data-build]').forEach(s=>s.onchange=()=>{state.answers['b'+s.dataset.build]=s.value;save()});
//3 audio numbers
const numRounds=[['n7','7'],['n3','3'],['n0','0'],['n10','10']];let numRound=state.answers.numRound||0;let numCorrect=state.answers.numCorrect||0;
function renderNum(){numRound=Math.min(numRound,numRounds.length-1);$('#num-rounds').innerHTML=numRounds.map((_,i)=>`<i class="dot ${i<numRound?'done':''} ${i===numRound?'current':''}"></i>`).join('');$('#num-input').value='';$('#num-feedback').textContent=numRound>=numRounds.length?'Готово!':''}
$('#num-play').onclick=()=>play(audio[numRounds[numRound][0]],$('#num-play'));
$('#num-submit').onclick=()=>{if(state.answers.numDone)return;const val=$('#num-input').value.trim();if(!val)return toast('Введите число');const ok=val===numRounds[numRound][1];if(ok){numCorrect++;$('#num-feedback').textContent='Верно!';$('#num-feedback').className='feedback ok'}else{$('#num-feedback').textContent=`Почти. Правильный ответ: ${numRounds[numRound][1]}`;$('#num-feedback').className='feedback bad'}numRound++;state.answers.numRound=numRound;state.answers.numCorrect=numCorrect;if(numRound>=numRounds.length){state.answers.numDone=true;setScore('numbers',numCorrect,4);$('#num-submit').disabled=true;$('#num-play').disabled=true;toast(`Аудирование: ${numCorrect}/4`)}else renderNum();save()};
renderNum();if(state.answers.numDone){$('#num-submit').disabled=true;$('#num-play').disabled=true;$('#num-feedback').textContent=`Готово: ${numCorrect}/4`;}
//4 number challenge
const ng=[{html:'<div class="num-visual">'+Array(4).fill('<i class="cup"></i>').join('')+'</div><div class="qtext">How many cups?</div>',a:'four'},{html:'<div class="qtext">six, seven, ___</div>',a:'eight'},{html:'<div class="qtext">Write 9 in words</div>',a:'nine'}];
$('#number-grid').innerHTML=ng.map((q,i)=>`<div class="number-card card">${q.html}<input class="mini-input" data-ng="${i}" placeholder="Type your answer"></div>`).join('');
$$('[data-ng]').forEach(x=>{x.value=state.answers['ng'+x.dataset.ng]||'';x.oninput=()=>{state.answers['ng'+x.dataset.ng]=x.value;save()}});
//5 days
let days=state.answers.daysOrder||['Thursday','Monday','Saturday','Tuesday','Friday','Sunday','Wednesday'];const dayCorrect=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];let dragDay=null;
function renderDays(){const b=$('#days-board');b.innerHTML=days.map(d=>`<div class="day-card" draggable="true" data-day="${d}">${d}</div>`).join('');$$('[data-day]').forEach(el=>{el.ondragstart=()=>{dragDay=el.dataset.day;el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const target=el.dataset.day;if(target===dragDay)return;const a=days.indexOf(dragDay),b=days.indexOf(target);days.splice(b,0,days.splice(a,1)[0]);state.answers.daysOrder=days;save();renderDays()};el.onclick=()=>{if(!state.answers.dayPick){state.answers.dayPick=el.dataset.day;el.style.outline='3px solid #6e63ff'}else{const a=days.indexOf(state.answers.dayPick),b=days.indexOf(el.dataset.day);days[a]=el.dataset.day;days[b]=state.answers.dayPick;delete state.answers.dayPick;state.answers.daysOrder=days;save();renderDays()}}})}
renderDays();
//6 sounds
const soundAnswers={hello:'h',nine:'ai',five:'ai',meet:'ee'};let soundPlaced=state.answers.soundPlaced||{};
function renderSounds(){const bins=[['h','/h/','house'],['ai','/aɪ/','bike'],['ee','/iː/','tree']];$('#sound-zone').innerHTML=bins.map(([id,t,ex])=>`<div class="sound-bin card" data-bin="${id}"><div class="sound-title">${t}</div><div class="subtitle">${ex}</div><div class="sound-items">${Object.keys(soundPlaced).filter(k=>soundPlaced[k]===id).map(k=>soundToken(k,true)).join('')}</div></div>`).join('');$('#sound-bank').innerHTML=Object.keys(soundAnswers).filter(k=>!soundPlaced[k]).map(k=>soundToken(k,false)).join('');$$('.sound-token').forEach(el=>{el.draggable=true;el.ondragstart=()=>el.dataset.drag=el.dataset.word;el.onclick=()=>play(audio[el.dataset.word])});$$('[data-bin]').forEach(bin=>{bin.ondragover=e=>e.preventDefault();bin.ondrop=e=>{e.preventDefault();const word=$$('.sound-token').find(x=>x.dataset.drag)?.dataset.word;if(word){soundPlaced[word]=bin.dataset.bin;state.answers.soundPlaced=soundPlaced;save();renderSounds()}}})}
function soundToken(w,inBin){return `<div class="sound-token" data-word="${w}">${w}<span style="margin-left:8px">🔊</span></div>`}
renderSounds();
//7 dialogue
$('#dialogue').innerHTML=`<div class="bubble a">Hi. <select class="inline-select" data-d="0"><option value="">...</option><option>I’m</option><option>You’re</option></select> Maya.</div><div class="bubble b">Hello, Maya. I’m Leo.</div><div class="bubble a"><select class="inline-select" data-d="1"><option value="">...</option><option>Are you</option><option>Am I</option></select> Leo?</div><div class="bubble b">Yes, <select class="inline-select" data-d="2"><option value="">...</option><option>I am</option><option>I’m</option></select>. Nice to meet you.</div><div class="bubble a">Nice to meet you.</div><div class="bubble b">Bye! See you <input class="gap-input" data-d="3" placeholder="tomorrow">.</div>`;
$$('[data-d]').forEach(x=>{x.value=state.answers['d'+x.dataset.d]||'';x.onchange=x.oninput=()=>{state.answers['d'+x.dataset.d]=x.value;save()}});
//8 mission
const mission=[['The woman’s name is…',['Emma','Mia'],'Emma'],['The man says…',['I’m Ben.','You’re Ben.'],"I’m Ben."],['At the end they say…',['See you tomorrow.','Good morning.'],'See you tomorrow.']];
$('#mission-qs').innerHTML=mission.map((q,i)=>`<div class="qrow"><div class="qtext">${i+1}. ${q[0]}</div><div class="options">${q[1].map(o=>`<button class="opt" data-mq="${i}" data-val="${esc(o)}">${esc(o)}</button>`).join('')}</div></div>`).join('');
$$('[data-mq]').forEach(b=>b.onclick=()=>{const q=b.dataset.mq;$$(`[data-mq="${q}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.answers['m'+q]=b.dataset.val;save()});$('#mission-play').onclick=()=>play(audio.mission,$('#mission-play'));
// check handlers
function checkScreen(i){if(i===1){let c=0;grammar.forEach((q,k)=>{const val=state.answers['g'+k];if(val===q[2])c++;$$(`[data-gq="${k}"]`).forEach(b=>{b.classList.toggle('correct',b.dataset.val===q[2]);b.classList.toggle('wrong',b.classList.contains('selected')&&b.dataset.val!==q[2])})});setScore('grammar',c,6);state.checked[1]=true;feedback(1,`${c}/6 — ${c===6?'Отлично!':'Проверьте отмеченные ответы.'}`,c===6)}
if(i===2){let c=0;builds.forEach((x,k)=>{if(state.answers['b'+k]===x[2])c++});const old=state.scores.grammar||[0,0];setScore('grammar',old[0]+c,old[1]+4);state.checked[2]=true;feedback(2,`${c}/4 — ${c===4?'Супер!':'Есть формы, которые стоит повторить.'}`,c===4)}
if(i===4){let c=0;ng.forEach((q,k)=>{const v=(state.answers['ng'+k]||'').trim().toLowerCase();if(v===q.a)c++;const el=$(`[data-ng="${k}"]`);el.style.borderColor=v===q.a?'#44dd91':'#ff7182'});const old=state.scores.numbers||[0,0];const baseAudio=state.answers.numDone?state.answers.numCorrect:0;setScore('numbers',baseAudio+c,(state.answers.numDone?4:0)+3);state.checked[4]=true;feedback(4,`${c}/3`,c===3)}
if(i===5){const c=days.filter((d,k)=>d===dayCorrect[k]).length;setScore('days',c,7);state.checked[5]=true;$$('.day-card').forEach((el,k)=>{el.classList.toggle('correct',days[k]===dayCorrect[k]);el.classList.toggle('wrong',days[k]!==dayCorrect[k])});feedback(5,`${c}/7 — ${c===7?'Идеальный порядок!':'Переставьте отмеченные дни.'}`,c===7)}
if(i===6){let c=0;Object.entries(soundAnswers).forEach(([w,a])=>{if(soundPlaced[w]===a)c++});setScore('pronunciation',c,4);state.checked[6]=true;feedback(6,`${c}/4 — ${c===4?'Отлично слышите звуки!':'Попробуйте ещё раз и прослушайте слова.'}`,c===4)}
if(i===7){const ans=["I’m",'Are you','I am','tomorrow'];let c=0;ans.forEach((a,k)=>{if((state.answers['d'+k]||'').trim().toLowerCase()===a.toLowerCase())c++});setScore('communication',c,4);state.checked[7]=true;feedback(7,`${c}/4`,c===4)}
if(i===8){let c=0;mission.forEach((q,k)=>{if(state.answers['m'+k]===q[2])c++;$$(`[data-mq="${k}"]`).forEach(b=>{b.classList.toggle('correct',b.dataset.val===q[2]);b.classList.toggle('wrong',b.classList.contains('selected')&&b.dataset.val!==q[2])})});const old=state.scores.communication||[0,0];setScore('communication',old[0]+c,old[1]+3);state.checked[8]=true;feedback(8,`${c}/3`,c===3)}save()}
$$('[data-check]').forEach(b=>b.onclick=()=>checkScreen(Number(b.dataset.check)));$$('[data-next]').forEach(b=>b.onclick=()=>show(state.screen+1));$$('[data-prev]').forEach(b=>b.onclick=()=>show(state.screen-1));
function renderProgress(){const defs=[['grammar','Grammar','G'],['numbers','Numbers','123'],['days','Days','M'],['pronunciation','Pronunciation','♫'],['communication','Communication','💬']];$('#skill-map').innerHTML=defs.map(([k,n,ic])=>{const [c,t]=state.scores[k]||[0,0],p=t?Math.round(c/t*100):0;return `<div class="skill card"><div class="icon">${ic}</div><strong>${n}</strong><div class="ring" style="--p:${p*3.6}deg"><span>${p}%</span></div><small>${c}/${t||'—'}</small></div>`}).join('')}
function totals(){let c=0,t=0;Object.values(state.scores).forEach(([a,b])=>{c+=a;t+=b});return[c,t]}
function renderFinal(){const [c,t]=totals(),p=t?Math.round(c/t*100):0;$('#score-ring').innerHTML=`<div class="score-ring" style="--score:${p*3.6}deg"><div><b>${c}</b><small>из ${t}</small></div></div>`;const defs=[['grammar','Grammar'],['numbers','Numbers'],['days','Days'],['pronunciation','Pronunciation'],['communication','Communication']];$('#breakdown').innerHTML=`<h2 style="margin-top:0">${p>=90?'Великолепно!':p>=70?'Очень хорошо!':'Хорошая тренировка!'}</h2>${defs.map(([k,n])=>{const [a,b]=state.scores[k]||[0,0],x=b?Math.round(a/b*100):0;return `<div class="bar-row"><strong>${n}</strong><div class="bar"><i style="width:${x}%"></i></div><span>${a}/${b}</span></div>`}).join('')}`}
$('#restart').onclick=()=>{localStorage.removeItem('wow_ef_1a_state');location.reload()};$('#review').onclick=()=>{const map=[[1,'grammar'],[3,'numbers'],[4,'days'],[5,'pronunciation'],[6,'communication'],[7,'communication']];const bad=map.find(([,k])=>{const [a,b]=state.scores[k]||[0,0];return b&&a<b});show(bad?bad[0]:0);toast('Открыто задание для повторения')};
show(state.screen||0);
