
const BASE_W=1600, BASE_H=900;
function fit(){const s=Math.min(innerWidth/BASE_W,innerHeight/BASE_H);document.getElementById('fit').style.transform=`translate(-50%,-50%) scale(${s})`}
addEventListener('resize',fit);fit();

const AUDIO={phrases:'assets/audio/phrases_1.mp3',numbers:'assets/audio/numbers_1.mp3',days:'assets/audio/days_1.mp3',pron:'assets/audio/pronunciation_1.mp3',listen1:'assets/audio/listening_1.mp3',listen2:'assets/audio/listening_2.mp3'};
const data={
 phrases:[['Hi','Привет'],['Hello','Здравствуйте / Привет'],['What’s your name?','Как тебя / вас зовут?'],['Nice to meet you','Приятно познакомиться'],['A cappuccino, please','Капучино, пожалуйста'],['A tea, please','Чай, пожалуйста'],['Thanks','Спасибо'],['Sorry','Извините / Простите']],
 grammar:[
  {q:'I ___ Helen',o:['am','are'],a:'am'},{q:'You ___ Tom',o:['am','are'],a:'are'},
  {q:'I ___ not Ellen',o:['am','are'],a:'am'},{q:'You ___ not Dom',o:['am','are'],a:'are'},
  {q:'___ I in class 2?',o:['Am','Are'],a:'Am'},{q:'___ you Mike?',o:['Am','Are'],a:'Are'},
  {q:'Are you Helen?',o:['Yes, I am','Yes, you are'],a:'Yes, I am'},{q:'Am I in your class?',o:['Yes, you are','Yes, I am'],a:'Yes, you are'},
  {q:'Are you Diana?',o:['No, I’m not','No, you aren’t'],a:'No, I’m not'},{q:'Am I in room 8?',o:['No, you aren’t','No, I’m not'],a:'No, you aren’t'}],
 numbers:[{q:'zero',o:['0','2','10'],a:'0'},{q:'three',o:['3','7','9'],a:'3'},{q:'five',o:['4','5','6'],a:'5'},{q:'seven',o:['1','7','8'],a:'7'},{q:'nine',o:['6','8','9'],a:'9'},{q:'one, two, ___',o:['three','five','ten'],a:'three'},{q:'seven, eight, ___',o:['nine','six','zero'],a:'nine'},{q:'eight, nine, ___',o:['ten','three','five'],a:'ten'}],
 days:[{q:'Monday →',o:['Tuesday','Friday','Sunday'],a:'Tuesday'},{q:'Tuesday →',o:['Wednesday','Monday','Saturday'],a:'Wednesday'},{q:'Wednesday →',o:['Thursday','Tuesday','Friday'],a:'Thursday'},{q:'Thursday →',o:['Friday','Sunday','Monday'],a:'Friday'},{q:'Friday →',o:['Saturday','Thursday','Tuesday'],a:'Saturday'},{q:'Saturday →',o:['Sunday','Friday','Monday'],a:'Sunday'},{q:'Goodbye, Tom. See you on ___',o:['Friday','five','tea'],a:'Friday'},{q:'See you ___',o:['tomorrow','cappuccino','Helen'],a:'tomorrow'}],
 pron:[{w:'hello',a:'/h/'},{w:'Helen',a:'/h/'},{w:'hi',a:'/h/'},{w:'I’m',a:'/aɪ/'},{w:'five',a:'/aɪ/'},{w:'nine',a:'/aɪ/'},{w:'meet',a:'/iː/'},{w:'tea',a:'/iː/'}],
 listening:[{q:'What does the speaker order?',o:['A cappuccino','A tea','Two teas'],a:'A cappuccino'},{q:'What name do you hear?',o:['Helen','Ellen','Diana'],a:'Helen'},{q:'Are you Diana?',o:['No, I’m not','Yes, you are','No, you aren’t'],a:'No, I’m not'},{q:'What does Tom order?',o:['A tea','A cappuccino','Three teas'],a:'A tea'},{q:'Tom or Dom?',o:['Tom','Dom','Mike'],a:'Tom'},{q:'What phrase do you hear?',o:['Nice to meet you','See you tomorrow','Good morning'],a:'Nice to meet you'},{q:'Which number do you hear?',o:['three','five','nine'],a:'five'},{q:'Which goodbye phrase do you hear?',o:['See you on Friday','See you on Monday','See you on Sunday'],a:'See you on Friday'}]
};
const MAX={phrases:8,grammar:10,numbers:8,days:8,pron:8,listening:8};
let state={screen:0,answers:{phrases:{},grammar:{},numbers:{},days:{},pron:{},listening:{}}};
try{const s=JSON.parse(localStorage.getItem('wow1a_v4'));if(s&&s.answers)state=s}catch(e){}
const app=document.getElementById('app');
function save(){localStorage.setItem('wow1a_v4',JSON.stringify(state))}
function score(sec){return Object.values(state.answers[sec]||{}).filter(Boolean).length}
function totalScore(){return Object.keys(MAX).reduce((n,k)=>n+score(k),0)}
function totalMax(){return Object.values(MAX).reduce((a,b)=>a+b,0)}
function header(){return `<div class="noise"></div><div class="header"><div class="wordmark"><div class="logo3d"><div class="wowmark">WOW</div><div class="brandline"></div><div class="brandtext"><strong>SCHOOL</strong><span>More English · Brighter Futures</span></div></div></div><div class="unitbadge"><span>English File Beginner</span><strong>Unit 1A</strong></div></div>`}
function panel(inner){return `${header()}<div class="mainpanel"><div class="content">${inner}</div></div>`}
function prog(n){return `<div class="progress"><strong>Прогресс ${n}/6</strong><div class="track"><i style="width:${n/6*100}%"></i></div></div>`}
function title(n,t,sub){return `<div class="titlebar"><div class="titlewrap"><h1><span class="n">${n}.</span> ${t}</h1><p>${sub}</p></div>${prog(n)}</div>`}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function choose(sec,i,value,correct){if(state.answers[sec][i]!==undefined)return;state.answers[sec][i]=value===correct;save();render()}
function optionButtons(sec,i,q){return `<div class="answers">${q.o.map(o=>{const done=state.answers[sec][i]!==undefined;const chosen=window._selected?.[sec]?.[i]===o;let cls='choice';if(done){if(o===q.a)cls+=' good';else if(chosen)cls+=' bad'}return `<button class="${cls}" data-sec="${sec}" data-i="${i}" data-v="${esc(o)}" ${done?'disabled':''}>${esc(o)}</button>`}).join('')}</div>`}
function taskGrid(sec,items){return `<div class="grid two" style="grid-template-rows:repeat(${Math.ceil(items.length/2)},1fr)">${items.map((q,i)=>{const done=state.answers[sec][i]!==undefined;return `<div class="task ${done?(state.answers[sec][i]?'correct':'wrong'):''}"><div class="qline"><div class="qtext">${esc(q.q)}</div><span class="qnum">${i+1}</span></div>${optionButtons(sec,i,q)}${done?`<div class="feedback ${state.answers[sec][i]?'good':'bad'}">${state.answers[sec][i]?'Верно':'Проверь ещё раз'}</div>`:''}</div>`}).join('')}</div>`}
window._selected={grammar:{},numbers:{},days:{},listening:{}};
function bindChoices(sec,items){document.querySelectorAll(`[data-sec="${sec}"]`).forEach(b=>b.onclick=()=>{const i=+b.dataset.i;window._selected[sec][i]=b.dataset.v;choose(sec,i,b.dataset.v,items[i].a)})}
async function audioExists(src){try{const r=await fetch(src,{method:'HEAD',cache:'no-store'});return r.ok}catch(e){return false}}
function audioCtl(key,label,id){return `<button class="audio" data-audio="${key}" data-status="${id}">▶ ${label}</button><span class="audioStatus" id="${id}">Проверка MP3…</span>`}
async function bindAudio(){for(const b of document.querySelectorAll('[data-audio]')){const key=b.dataset.audio,src=AUDIO[key],st=document.getElementById(b.dataset.status);const ok=await audioExists(src);if(!ok){b.classList.add('missing');b.disabled=true;st.textContent='Нужен реальный британский MP3';continue}st.textContent='British English · MP3';b.onclick=async()=>{try{st.textContent='Воспроизведение…';const a=new Audio(src+'?v=4');await a.play();a.onended=()=>st.textContent='Готово к повтору'}catch(e){st.textContent='Не удалось воспроизвести MP3'}}}}
function nav(next,label='Далее →'){return `<button class="next" id="next">${label}</button>`}
function setScreen(n){state.screen=n;save();render()}
function start(){app.innerHTML=panel(`<div class="hero"><div><div class="heroKicker">Unit Review · Lesson 1A</div><h1>A cappuccino,<span>please</span></h1><p>Проверочная работа только по материалу Lesson 1A: фразы, verb be с I / you, numbers 0–10, days of the week, pronunciation и listening.</p><div class="heroBtns"><button class="btn primary" id="start">Начать →</button><button class="btn secondary" id="reset">Сбросить прогресс</button></div></div><div class="visual"><div class="blob"><div class="saucer"></div><div class="cup"></div><div class="tag a">6 блоков</div><div class="tag b">British MP3</div></div></div></div>`);document.getElementById('start').onclick=()=>setScreen(1);document.getElementById('reset').onclick=()=>{state={screen:0,answers:{phrases:{},grammar:{},numbers:{},days:{},pron:{},listening:{}}};save();render()}}
function phrases(){app.innerHTML=panel(`${title(1,'Words & Phrases','Выбери правильный перевод')}
<div class="selectrow" style="margin-top:8px;flex:1;align-content:start">${data.phrases.map((p,i)=>{const done=state.answers.phrases[i]!==undefined;return `<div class="task phrase-card ${done?(state.answers.phrases[i]?'correct':'wrong'):''}"><div class="phrase">${esc(p[0])}</div><select class="phrase-select" data-p="${i}" ${done?'disabled':''}><option value="">Выбери перевод</option>${data.phrases.map(x=>`<option value="${esc(x[1])}">${esc(x[1])}</option>`).join('')}</select>${done?`<div class="feedback ${state.answers.phrases[i]?'good':'bad'}">${state.answers.phrases[i]?'Верно':'Ошибка'}</div>`:''}</div>`}).join('')}</div>
<div class="footeractions"><div class="leftactions">${audioCtl('phrases','Послушать фразы','stp')}</div>${nav(2)}</div>`);document.querySelectorAll('[data-p]').forEach(s=>s.onchange=()=>{const i=+s.dataset.p;if(!s.value)return;state.answers.phrases[i]=s.value===data.phrases[i][1];save();render()});document.getElementById('next').onclick=()=>setScreen(2);bindAudio()}
function grammar(){app.innerHTML=panel(`${title(2,'Grammar Check','verb be · только I / you')}${taskGrid('grammar',data.grammar)}<div class="footeractions"><span class="smallnote">I am · You are · I’m not · You aren’t · Am I? · Are you?</span>${nav(3)}</div>`);bindChoices('grammar',data.grammar);document.getElementById('next').onclick=()=>setScreen(3)}
function numbers(){app.innerHTML=panel(`${title(3,'Numbers 0–10','Узнай число и продолжи последовательность')}${taskGrid('numbers',data.numbers)}<div class="footeractions"><div class="leftactions">${audioCtl('numbers','Послушать числа','stn')}</div>${nav(4)}</div>`);bindChoices('numbers',data.numbers);document.getElementById('next').onclick=()=>setScreen(4);bindAudio()}
function days(){app.innerHTML=panel(`${title(4,'Days & Goodbye','Дни недели и фразы прощания')}${taskGrid('days',data.days)}<div class="footeractions"><div class="leftactions">${audioCtl('days','Послушать дни','std')}</div>${nav(5)}</div>`);bindChoices('days',data.days);document.getElementById('next').onclick=()=>setScreen(5);bindAudio()}
function pron(){const bins=['/h/','/aɪ/','/iː/'];app.innerHTML=panel(`${title(5,'Sound Sort','Распредели слова по звукам')}<div class="sortarea">${bins.map(b=>`<div class="bin" data-bin="${b}"><strong>${b}</strong><div class="binwords">${data.pron.map((x,i)=>state.answers.pron[i]!==undefined&&x.a===b?`<button class="word ${state.answers.pron[i]?'good':'bad'}" disabled>${esc(x.w)}</button>`:'').join('')}</div></div>`).join('')}</div><div class="wordbank">${data.pron.map((x,i)=>state.answers.pron[i]===undefined?`<button class="word" data-word="${i}">${esc(x.w)}</button>`:'').join('')}</div><div class="footeractions"><div class="leftactions">${audioCtl('pron','Послушать образцы','stpr')}<span class="audioStatus" id="sortHint">Сначала выбери слово, затем звук</span></div>${nav(6)}</div>`);let sel=null;document.querySelectorAll('[data-word]').forEach(w=>w.onclick=()=>{document.querySelectorAll('[data-word]').forEach(x=>x.classList.remove('sel'));w.classList.add('sel');sel=+w.dataset.word});document.querySelectorAll('[data-bin]').forEach(b=>b.onclick=()=>{if(sel===null)return;state.answers.pron[sel]=data.pron[sel].a===b.dataset.bin;save();render()});document.getElementById('next').onclick=()=>setScreen(6);bindAudio()}
function listening(){app.innerHTML=panel(`${title(6,'Listening Mission','Слушай и выбирай ответ · только Lesson 1A')}${taskGrid('listening',data.listening)}<div class="footeractions"><div class="leftactions">${audioCtl('listen1','Диалог 1','stl1')}${audioCtl('listen2','Диалог 2','stl2')}</div>${nav(7,'Результат →')}</div>`);bindChoices('listening',data.listening);document.getElementById('next').onclick=()=>setScreen(7);bindAudio()}
function results(){const keys=['phrases','grammar','numbers','days','pron','listening'],labels={phrases:'Words & Phrases',grammar:'Grammar',numbers:'Numbers',days:'Days & Goodbye',pron:'Pronunciation',listening:'Listening'};const total=totalScore(),max=totalMax(),pct=Math.round(total/max*100),sorted=[...keys].sort((a,b)=>score(b)/MAX[b]-score(a)/MAX[a]),best=sorted[0],weak=sorted.at(-1);app.innerHTML=panel(`<div class="titlebar"><div class="titlewrap"><h1>Your <span class="n">Results</span></h1><p>Итоги проверочной работы по Lesson 1A</p></div><div class="progress"><strong>Готово</strong><div class="track"><i style="width:100%"></i></div></div></div><div class="results"><div class="ring" style="--pct:${pct}"><strong>${pct}%</strong><span>общий результат</span></div><div><div class="resultlist">${keys.map(k=>{const p=Math.round(score(k)/MAX[k]*100);return `<div class="resrow"><label>${labels[k]}</label><div class="resbar"><i style="width:${p}%"></i></div><b>${score(k)}/${MAX[k]}</b></div>`}).join('')}</div><div class="coach"><div><strong>Сильная сторона</strong><p>${labels[best]} — лучший результат в этой попытке.</p></div><div><strong>Что повторить</strong><p>${labels[weak]} — сюда стоит вернуться ещё раз.</p></div></div><div class="heroBtns"><button class="btn primary" id="retry">Пройти ещё раз</button><button class="btn secondary" id="home">На главную</button></div></div></div>`);document.getElementById('retry').onclick=()=>{state.answers={phrases:{},grammar:{},numbers:{},days:{},pron:{},listening:{}};setScreen(1)};document.getElementById('home').onclick=()=>setScreen(0)}
function render(){[start,phrases,grammar,numbers,days,pron,listening,results][state.screen||0]()}
render();
